# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lyssa Freese
email: emfreese [at] mit.edu
description: I am a PhD student researching the intersection of atmospheric chemistry, energy systems, climate, and policy at the Massachusetts Institute of Technology. I work with Noelle Selin in the Department of Earth, Atmosphere and Planetary Sciences. My research aims to understand the influence climate has on historical and future air quality, the impacts that humans have had on the chemical composition of the atmosphere, and what policies and energy decisions are best for mitigating climate change and air pollution. Prior to starting my PhD, I worked at the Rock Energy and Environment institute in Beijing, China; for Green Camel Bell in Lanzhou, China; and for the Wilson Center's China Environment Forum in Washington, D.C. I graduated with a B.Sc. in Science, Technology and International Affairs from Georgetown University's School of Foreign Service. If you are interested in any of these topics, please feel free to get in touch!

twitter_username: LyssaFreese
github_username: lfreese
minimal_mistakes_skin: dirt
search: true

# Build settings
layout: splash
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 1 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  avatar : "/assets/images/Head-shot-square.jpeg"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

header:
  image: "/assets/images/masks.jpg"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: splash
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
